# Generated by Django 5.2.6 on 2025-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainInterface', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'module', 'period')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='period',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3'), ('Term 4', 'Term 4')], default='Term 1', max_length=50),
        ),
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('poor', 'Poor'), ('medium', 'Medium/Average'), ('good', 'Good')], default='medium', max_length=10),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='is_present',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='session_type',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='time',
        ),
    ]
